---

- hosts: all
  become: true
  tasks:

  - name: update repository index on any Linux Distribution
    package:
      update_cache: yes

  - name: install vim package on any Linux Distribution
    package:
      name: vim
      state: latest
