---

- hosts: all
  become: true
  tasks:

  - name: install vim package on any Linux Distribution
    package:
      name: 
        - "{{ package_name }}"
      state: latest
      update_cache: yes
