---

- hosts: 192.168.*
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

  - name: install vim package
    apt:
      name: vim
    when: ansible_distribution in ["Ubuntu","Debian"]
