---

- hosts: all
  become: true
  tasks:

  - name: remove vim package on Debian/Ubuntu
    apt:
      name: vim
      state: absent
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: remove vim package on CentOS
    yum:
      name: vim
      state: absent
    when: ansible_distribution in ["CentOS"]
